#!/usr/bin/env ruby
require 'highline/import'

menu_prompt = <<EOS
1. Add a happy hour location
2. List all happy hour locations
3. Exit management menu
EOS

if ARGV.length < 1
  print "[Help] Run as: ./happy_nash manage"
elsif ARGV.length == 1
  if ARGV[0] != 'manage'
    print "[Help] Run as: ./happy_nash manage"
  else
    choose do |menu|
      menu.prompt = ""
      menu.choice('Add a happy hour location') { say("") }
      menu.choice('List all happy hour locations') { say("No locations found. Add a location.\n#{ menu_prompt}") }
      menu.choice('Exit management menu') { say("You have successfully exited the management menu.") }
    end
  end
end
